"""Module for system engineering throughputs curves"""
try:
    # version.py is auto-generated by sconsUtils
    from .version import *  # noqa: F403
except:
    __version__ = "unknown"

from .bandpassUtils import *
from .sedUtils import *
from .m5Utils import *
